version: 2.1

orbs:
  codecov: codecov/codecov@3.2.4
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test

      - codecov/upload:
          file: ./target/site/jacoco/jacoco.xml

  docs:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: OpenJDK-PPA
          command: sudo add-apt-repository ppa:openjdk-r/ppa
      - run:
          name: Update APT
          command: sudo apt-get update
      - run:
          name: OpenJDK-Install
          command: sudo apt-get install openjdk-11-jdk-headless -y
      - run:
          name: Build the docs with javadoc
          command: javadoc -d docs src/main/java/fr/univavignon/pokedex/api/*
      - persist_to_workspace:
          root: .
          paths: docs

  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: docs/
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config --global user.email "yassine.aadssi@alumni.univ-avignon.fr"
            git config --global user.name "Yassine-AADSSI"
      - add_ssh_keys:
          fingerprints:
            - "dc:ff:8e:de:95:78:8f:00:9d:23:f4:0b:6a:61:4e:ca"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist docs

workflows:
  main:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master
      - docs:
          requires:
            - build-and-test
      - docs-deploy:
          requires:
            - docs
          filters:
            branches:
              only: master